accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('',views.home,name='home'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('login/',views.userLogin,name='login'),
    path('register/',views.register,name='register'),
    path('userAccounts/',views.userAccounts,name='userAccounts'),
    path('editUser/<int:userID>?<path:backurl>', views.editUser, name='editUser'),
    path('editPass/<int:userID>/',views.editPass,name='editPass'),
    path('incidentEntry/',views.incidentEntry,name='incidentEntry'),
    path('incidentReportEntry/',views.incidentReportEntry,name='incidentReportEntry'),
    path('incidentReportEdit/<int:entryID>/',views.incidentReportEdit,name='incidentReportEdit'),
    path('dashBoard/',views.dashBoard,name='dashBoard'),
    path('viewReports/',views.viewReports,name='viewReports'),
    path('viewReferrals/',views.viewReferrals,name='viewReferrals'),
    path('referralEdit/<int:referralId>',views.referralEdit,name='referralEdit'),
    path('viewReport_R/<int:reportID>',views.viewReport_R,name='viewReport_R'),
    path('timeCard', views.timeCard, name='timeCard'),
    path('locations/', views.locations,name='locations' ),

]

anzen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('SASPadmin/', admin.site.urls),
    path('',include('accounts.urls')),
]

accounts/models.py
from operator import mod
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

# Create your models here.



class CustomAccountManager(BaseUserManager):

    def create_superuser(self,email,password, **other_fields):

        other_fields.setdefault('is_superuser',True)
        other_fields.setdefault('is_staff',True)

        return self.create_user(email,password, **other_fields)

    def create_user(self,email,password, **other_fields):
        email = self.normalize_email(email)
        user = self.model(email = email, **other_fields)
        user.set_password(password)
        user.save()
        return user




class User(AbstractBaseUser,PermissionsMixin):
    badgeNo = models.IntegerField(null=True)
    firstName = models.CharField(max_length=50,null=True)
    lastName = models.CharField(max_length=50,null=True)
    dob = models.DateField( auto_now=False, auto_now_add=False,null=True)
    collegeId = models.IntegerField(null=True)
    status = models.CharField(default='Active',max_length=50, choices=[('Active','Active'),('Not Active','Not Active')])
    email = models.EmailField( max_length=254, unique=True)
    position = models.CharField(max_length=150,null=True,default="Probationary Member")
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=True)
    objects= CustomAccountManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        ret = str(self.firstName)+","+str(self.lastName)
        return ret

class inceident (models.Model):
    inceidentName = models.CharField(max_length=150,null=True)
    def __str__(self):
        return self.inceidentName

class location (models.Model):
    locationName = models.CharField(max_length=150,null=True)
    def __str__(self):
        return self.locationName


class incidentReport (models.Model):
    reportedBy  = models.ForeignKey(User,null=False,on_delete=models.PROTECT)
    inceident = models.CharField(max_length=150,null=False)
    date = models.DateField(auto_now=False, auto_now_add=False,null=False)
    receivedTime = models.TimeField(auto_now=False, auto_now_add=False,)
    enrouteTime = models.TimeField(auto_now=False, auto_now_add=False,)
    arivedTime = models.TimeField(auto_now=False, auto_now_add=False,)
    clearTime = models.TimeField(auto_now=False, auto_now_add=False,)
    location = models.CharField(max_length=150,null=False)
    locationDetail = models.CharField(max_length=150, null=True)

    summary = models.TextField()
    def __str__(self):
        ret = str(self.inceident)+' '+str(self.date)+' '+str(self.location)
        return ret

class referral(models.Model):
    incidentReport = models.ForeignKey(incidentReport,null=False,on_delete=models.PROTECT)
    firstName = models.CharField(max_length=150,null=False)
    middleInitial = models.CharField(max_length=150,null=False)
    ICID = models.CharField(max_length=150,null=False)
    dob = models.DateField(auto_now=False, auto_now_add=False,null=False)
    address = models.TextField()
    phoneNo = models.CharField(max_length=150,null=False)

    def __str__(self):
        ret = str(self.inceident)+' '+str(self.firstName)+','+str(self.middleInitial)
        return ret

class timeCard(models.Model):

    who = models.ForeignKey(User,null=False,on_delete=models.PROTECT)
    start = models.DateTimeField(auto_now=False,null=False)
    end = models.DateTimeField(auto_now=False,null=False)
    duration = models.CharField(max_length=150,null=False)
    submitedDate = models.DateTimeField(auto_now=True,null=False)
    approval =  models.CharField(max_length=150,default="Pending")
    note = models.TextField(null=True) 
    def __str__(self):
        ret = str(self.who)+' '+str(self.submitedDate)
        return ret

class clockedIn(models.Model):

    who = models.ForeignKey(User,null=False,on_delete=models.PROTECT)
    start = models.DateTimeField(auto_now=True,null=False)
    
    def __str__(self):
        ret = str(self.who)+' '+str(self.start)
        return ret

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from . import models
User = get_user_model()

class DateInput(forms.DateInput):
    input_type = 'date'


class TimePickerInput(forms.TimeInput):
        input_type = 'time'

class creatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['badgeNo','firstName','lastName','dob','collegeId','status','email', 'password1','password2' ]
        widgets = {
            'dob': DateInput(),
        }

class editUserPasword(UserCreationForm):
    class Meta:
        model = User
        fields = ['password1','password2']

accounts/views.py
from datetime import datetime

from time import strftime
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from . import forms,models
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import HttpResponseRedirect





# Create your views here.

def home(request):

    return render(request, 'accounts/public/home.html')

def logout(request):
    logout(request)
    return redirect('home')

def userLogin(request):

    if request.method == 'POST' :
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate( request,email=email, password= password)

        if user is not None :
            login(request,user)
            return redirect('dashBoard')
        else:
            # write code to tell user login unsccessful
            print("failed")

    return render(request, 'accounts/account_management/login.html')


@login_required(login_url='login')
def register(request):
    form = forms.creatUserForm(request.POST)
    context ={'regisForm':form }
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("userAccounts")
        else:
            messages.error(request,"Passwords did not match or were two short.")


    return render(request,'accounts/account_management/register.html',context)

@login_required(login_url='login')
def editPass(request,userID):
    curRec = models.User.objects.get(id =userID )
    form = forms.editUserPasword(request.POST,instance= curRec )
    context ={'regisForm':form }
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("userAccounts")
        else:
            messages.error(request,"Passwords did not match or were two short.")


    return render(request,'accounts/account_management/editpass.html',context)
@login_required(login_url='login')
def userAccounts(request):
    print(request)
    users = models.User.objects.all()
    context ={'users':users }
    if  request.method == 'POST':
        data = request.POST
        lisst = list(data)
        dat = lisst[1]

        buttonFunc = dat[0]
        userID = dat[1:]
        curRec = models.User.objects.get(id =userID )
        if buttonFunc == '0':

            redirect_url = reverse('editUser', args=[userID,request.get_full_path()])
            # parameters = urlencode(curRec)
            return redirect(redirect_url)
        elif buttonFunc == '1':
            curRec.delete()
        elif buttonFunc == '2':
            curstat =curRec.status
            if curstat == 'Active':
                curRec.status = 'Not Active'
                curRec.save()
            elif curstat == 'Not Active':
                curRec.status = 'Active'
                curRec.save()
            else:
                curRec.status = 'Active'
                curRec.save()
        elif buttonFunc == '3':
            redirect_url = reverse('editPass', args=[userID])
            return redirect(redirect_url)
        elif buttonFunc == '4':
            curUser = models.User.objects.get(id =userID )
            if curUser.position == "Probationary Member":
                curUser.position = "Junior Member"
                curUser.save()
                message = curUser.firstName+" "+curUser.lastName+" "+"Is Promoted !!!"
                messages.success(request, message)
                return HttpResponseRedirect(reverse("userAccounts"))
            elif curUser.position == "Junior Member":
                curUser.position = "Senior Member"
                curUser.save()
                message = curUser.firstName+" "+curUser.lastName+" "+"Is Promoted !!!"
                messages.success(request, message)
                return HttpResponseRedirect(reverse("userAccounts"))
            elif curUser.position == "Senior Member":
                curUser.position = "Executive Board Member"
                curUser.save()
                message = curUser.firstName+" "+curUser.lastName+" "+"Is Promoted !!!"
                messages.success(request, message)
                return HttpResponseRedirect(reverse("userAccounts"))
            else:
                messages.success(request, "Can not be promoted further! ")
                return HttpResponseRedirect(reverse("userAccounts"))


        elif buttonFunc == '5':
            curUser = models.User.objects.get(id =userID )
            if curUser.position == "Junior Member":
                curUser.position = "Probationary Member"
                curUser.save()
                message = curUser.firstName+" "+curUser.lastName+" "+"Is Deomoted !!!"
                messages.success(request, message)
                return HttpResponseRedirect(reverse("userAccounts"))
            elif curUser.position == "Senior Member":
                curUser.position = "Junior Member"
                curUser.save()
                message = curUser.firstName+" "+curUser.lastName+" "+"Is Deomoted !!!"
                messages.success(request, message)
                return HttpResponseRedirect(reverse("userAccounts"))
            elif curUser.position == "Executive Board Member":
                curUser.position = "Senior Member"
                curUser.save()
                message = curUser.firstName+" "+curUser.lastName+" "+"Is Deomoted !!!"
                messages.success(request, message)
                return HttpResponseRedirect(reverse("userAccounts"))
            else:
                messages.success(request, "Can not be deomoted further! ")
                return HttpResponseRedirect(reverse("userAccounts"))

    return render(request,'accounts/account_management/userAccounts.html',context)
@login_required(login_url='login')
def editUser(request,userID,backurl):

    curRec = models.User.objects.get(id =userID)
    if request.method == 'POST':
        badgeNo = request.POST.get("badgeNo")
        firstName = request.POST.get("firstName")
        lastName = request.POST.get("lastName")
        dob = request.POST.get("dob")
        collegeId = request.POST.get("collegeId")
        status = request.POST.get("status")
        email = request.POST.get("email")

        curRec.badgeNo = badgeNo
        curRec.firstName = firstName
        curRec.lastName = lastName
        curRec.dob = dob
        curRec.collegeId = collegeId
        curRec.status = status
        curRec.email = email

        curRec.save()
        return redirect('userAccounts')

    return render(request,'accounts/account_management/editUser.html',{'user':curRec, 'backurl':backurl})

@login_required(login_url='login')
def incidentEntry(request):
    inceidents = models.inceident.objects.all()
    if request.method =='POST':
        if'newInceident' in request.POST:
            inceident = request.POST['newInceident']
            models.inceident.objects.create(inceidentName=inceident)
        else:
            data = request.POST
            lisst = list(data)
            dat = lisst[1]
            count=0
            buttonFunc =''
            inceidentId =''
            inceidenteditName =''
            for i in dat:
                if i != ',':
                    if count == 0:
                        buttonFunc=buttonFunc+i
                    elif count == 1:
                        inceidentId = inceidentId+i
                    elif count == 2:
                        inceidenteditName = inceidenteditName+i
                else:
                    count = count +1

            print(buttonFunc)
            print(inceidentId)
            print(inceidenteditName)
            if buttonFunc == '0':
                inceToedit = models.inceident.objects.get(id=inceidentId)
                inceToedit.inceidentName = inceidenteditName
                inceToedit.save()
            elif buttonFunc == '1':
                inceToDel = models.inceident.objects.get(id=inceidentId)
                inceToDel.delete()

    return render(request,'accounts/reports/inceidentsEntry.html',{'inceidents':inceidents})


@login_required(login_url='login')
def dashBoard(request):
    CoI = models.clockedIn.objects.all()
    clockedIN =[]
    for c in CoI:
        clockedIN.append(c.who)



    if request.POST.get("ClockButton") == "clockIn":
        CoI = models.clockedIn.objects.all()
        clockedIN =[]
        for c in CoI:
            clockedIN.append(c.who)
        if not( request.user in clockedIN):
            clockin = models.clockedIn.objects.create(who=request.user,start= datetime.strptime(request.POST.get("timeNow").replace("T", " "),"%Y-%m-%d %H:%M"))
            clockin.save()
            CoI = models.clockedIn.objects.all()
            return HttpResponseRedirect(reverse("dashBoard"))

    if request.POST.get("ClockButton") == "clockOut":
        clockInRec = models.clockedIn.objects.get(who = request.user)
        endDT = datetime.strptime(request.POST.get("timeNow").replace("T", " "),"%Y-%m-%d %H:%M")
        # print(type(clockInRec.start))
        # print(endDT)
        pop = endDT-clockInRec.start
        print(round(pop.seconds/3600))
        print(round(pop.seconds/60))
        hr = str(round(pop.seconds/3600)).rjust(2, '0')
        min = str(round(pop.seconds/60)).rjust(2, '0')
        dur = hr+":"+min
        models.timeCard.objects.create(who =request.user, start =clockInRec.start,end = endDT,duration = dur  )
        clockInRec.delete()
        CoI = models.clockedIn.objects.all()
        return HttpResponseRedirect(reverse("dashBoard"))


    return render(request,'accounts/reports/dashBoard.html',{'clockedIN':clockedIN})

@login_required(login_url='login')
def incidentReportEntry(request):
    inceidents=models.inceident.objects.all()
    locations = models.location.objects.all()
    if request.method == 'POST':
        print(request.POST)
        #inceident record

accounts/templates/accounts/account_management/editUser.html
{% extends 'accounts/index.html' %}

{% block header %}
Edit User
{% endblock header %}


{% block content %}
<div class="registration">
    <form method="POST" action="" class="registrationForm">
        {% csrf_token %}
        <div>
            <p>Badge No.</p>
            <input type="number" value="{{ user.badgeNo }}" name="badgeNo" required>
        </div>
        <div>
            <p>First Name</p>
            <input type="text" value="{{ user.firstName }}"name="firstName" required>
        </div>
        <div>
            <p>Last Name</p>
            <input type="text" value="{{ user.lastName }}"name="lastName" required>
        </div>
        <div>
            <p>Date</p>
            <input type="date"name="dob" required>
        </div>
        <div>
            <p>College ID</p>
            <input type="number" value="{{ user.collegeId }}"name="collegeId" required>
        </div>
        <div>
            <p>Status</p>
            <select name="status" id="id_status" required>
                <option value="Active">Active</option>
                <option value="Not Active">Not Active</option>
             </select>
        </div>
        <div>
            <p>Email</p>
            <input type="email" value="{{ user.email }}"name="email" required>
        </div>

        <input type="submit" value="Update" class="registerButton">

    </form>
</div>
{% endblock content %}

{% block script %}
<script nonce="{{request.csp_nonce}}">


    var dob = new Date('{{user.dob}}');
    console.log('{{user.dob}}');
    dob.getDate()
    year  = dob.getFullYear();
    month = (dob.getMonth() + 1).toString().padStart(2, "0");
    day   = dob.getDate().toString().padStart(2, "0");
    var dob2 = (year+"-"+month+"-"+day)

    const status = '{{user.status}}';




    const ele_dob = document.querySelector('input[type="date"]');

    const ele_status = document.getElementById('id_status');



    ele_dob.value=dob2;

    ele_status.value=status;





</script>
{% endblock script %}

accounts/templates/accounts/account_management/editpass.html
{% extends 'accounts/index.html' %}

{% block header %}
Change Password
{% endblock header %}


{% block content %}
    <div class="registration">
        <form method="POST" action="" class="registrationForm">
            {% csrf_token %}
             {% for field in regisForm %}
            <div>
                <p>{{field.label}}</p>
                {{field}}
            </div>
            {% endfor %}
            {% for message in messages %}
            <script>
                alert('{{ message }}')
            </script>
            {% endfor %}
            <input type="submit" value="Register" class="registerButton">

        </form>
    </div>
    
{% endblock content %}

{% block script %}
<script>
    
</script>
{% endblock script %}

accounts/templates/accounts/account_management/login.html
{% extends 'accounts/index.html' %}

{% block header %}
Login
{% endblock header %}

{% block log %}
{% endblock %}

{% block content %}
    <div class='loginDiv'>
        <form method="POST" action="" class="loginDivform">
            {% csrf_token %}
            <div class='title'>
                <p>
                    Member login
                </p>
            </div>
            <div class="emailDiv">
                <input type="email" placeholder="Email" name="email">
            </div>
            <div class="passwordDiv">
                <input type="password"  name="password" placeholder="Password">
            </div>
            <div class="loginButtonDiv">
                <input type="submit" class="muleInspectionEntrybutton" value="Login">
            </div>
        </form>
    </div>
{% endblock content %}

accounts/templates/accounts/account_management/register.html
{% extends 'accounts/index.html' %}

{% block header %}
Accounts
{% endblock header %}


{% block content %}
    <div class="registration">
        <form method="POST" action="" class="registrationForm">
            {% csrf_token %}
             {% for field in regisForm %}
            <div>
                <p>{{field.label}}</p>
                {{field}}
            </div>
            {% endfor %}
            {% for message in messages %}
            <script>
                alert('{{ message }}')
            </script>
            {% endfor %}
            <input type="submit" value="Register" class="registerButton">

        </form>
    </div>
    
{% endblock content %}

{% block script %}
<script>
    
</script>
{% endblock script %}

accounts/templates/accounts/account_management/userAccounts.html
{% extends 'accounts/index.html' %}

{% block header %}
Accounts
{% endblock header %}


{% block content %}
<div id="popup1" class="overlay">
	<div class="popup">
		<h2>Pop Up</h2>
		<a class="close" id="popUpClose" href="#">&times;</a>
		<div class="content">
            {% for message in messages  %}
                <p>{{message}}</p>
            {% endfor %}
		</div>
	</div>
</div>

    <div class="accountsDisplay">
        <H1 style="colourBlue">
            SASP Members
        </H1>
        <form class="accountsDisplayForm" action="" method="POST">
            {% csrf_token %}

            <table >
                <tr>
                    <th>Badge No.</th>
                    <th>Rank</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Dob</th>
                    <th>College ID</th>
                    <th>Status</th>
                    <th>Email</th>
                    <th><a href="{% url 'register' %}"><button type="button" class="newInceidentButton" style="width: 100%;">Creat Account</button></a></th>
                </tr>
                {% for user in users %}
                <tr>
                    <td> {{ user.badgeNo }}</td>
                    <td>{{ user.position }}</td>
                    <td>{{ user.firstName }}</td>
                    <td>{{ user.lastName }}</td>
                    <td>{{ user.dob }}</td>
                    <td>{{ user.collegeId }}</td>
                    <td>{{ user.status }}</td>
                    <td> {{ user.email }}</td>
                    <td>
                        <button type="submit" class="editButton" value="edit" name="0{{user.id}}">Edit</button>
                        <button type="submit" class="deleteButton" value="delete" name="1{{user.id}}">Delete</button>
                        <button type="submit" class="editButton" value="promote"  name="4{{user.id}}">Promote</button>
                        <button type="submit" class="deleteButton" value="demote"  name="5{{user.id}}">Demote</button>
                        <button type="submit" class="statusButton" value="changestat" name="2{{user.id}}"> Change Status</button>
                        <button type="submit" class="passButton" value="changepass" name="3{{user.id}}"> Change Password</button>
                    </td>
                </tr>
                {% endfor %}

            </table>


        </form>
    </div>
{% endblock content %}

{% block script %}
<script nonce="{{request.csp_nonce}}">
    {% if messages  %}
    var popUp = document.getElementById("popup1")
    popUp.style.visibility = "visible";
    popUp.style.opacity = "1";
    document.getElementById("popUpClose").addEventListener('click', function () {
        popUp.style.visibility = "hidden";
        popUp.style.opacity = "0";
        });
    {% endif %} 

</script>
{% endblock script %}